### ISSUE TITLE
Anonymous gist creation no longer works

### ISSUE THREAD

**Issue by stasm** [projectfluent/play#3]
As of mid-March, GitHub [no longer allows anonymous creation of gists](https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/) via the web UI nor the API. This affects the Playground's ability to save the editor state to the cloud for sharing with other people.

There are two ways to solving this:

  1. Enable authentication. We could use the [react-github-login](https://github.com/checkr/react-github-login) component or rollout something more advanced, like [Auth0](https://auth0.com/docs/connections/social/github) which also integrates with react quite nicely.

  2. Change the storage backend. There are a number of anonymous cloud store solutions for JSON. A quick Google search came up with https://jsonbin.io/ and https://www.jsonstore.io/. This approach is possibly easier to implement and also offers the same UX as we used to have: no auth required. However it comes with two major drawbacks:

      - We might run into the same problem later in the future if the storage solution we choose sunsets or introduces the auth requirement to combat spam.

      - We'd want to keep the `?gist` param around to allow reading gists created in the past. And we'd need to add new code to handle the new storage solution. We'd end up with two code paths doing the same thing which is likely to end up being a maintenance headache.

My recommendation is to bite the bullet and go with `react-github-login`.

**Comment by Pike** [comment]
I was wondering how that worked a while back, and now I know.

I agree that we should just go with auth. I'm having doubts on react-github-login, there's open issues about its license, no existing dependents on npm, I would hate to bet on an unmaintained project. If Auth0 goes away, we have bigger problems, so maybe that's a safer choice for us?

**Comment by stasm** [comment]
We might need to host projectfluent.org under `https://` in order for auth to work. Which GitHub doesn't support for gh-pages using custom domains.

**Comment by rugk** [comment]
> We might need to host projectfluent.org under https:// in order for auth to work. Which GitHub doesn't support for gh-pages using custom domains.

Fortunately, that is a thing of the past. :smile:

**Comment by stasm** [comment]
Yes, it's really great that GitHub allows HTTPS for custom domains now. We've been using it since day one.
