### ISSUE TITLE
"Share as gist" throws exception and does not work

### ISSUE THREAD

**Issue by rugk** [projectfluent/play#6]
STR:
1. Click on "Share via Gist"

Happens:
For the user: Nothing visible. (This **is bad**! There should be user feedback even in the case of an error.)

JS:
```
 ReferenceError: regeneratorRuntime is not defined[Learn More] actions.js:53:11

    o actions.js:53 t2Redux
    s15React
    An (index):1018 

```

![image](https://user-images.githubusercontent.com/11966684/51431470-742f3b00-1c29-11e9-86b0-892477f420ec.png)

Expected:
Error or so.

Or make it work, but that may be hard due to https://github.com/projectfluent/play/issues/3

**Comment by stasm** [comment]
The exact error here related to the missing `regeneratorRuntime` was fix along with #7. I forgot to close this issue. The larger problem of not being to save gists anonymously will be fixed in #3.
