### ISSUE TITLE
Cannot load gist

### ISSUE THREAD

**Issue by rugk** [projectfluent/play#7]
It seems it even cannot load gists anymore. When I try to do so, I get timeouts or similar JS errors similar to https://github.com/projectfluent/play/issues/6

* One old link here https://projectfluent.io/play/?gist=400ca1160898d72f5935796a9982b22b results in server/response timeouts.
* One [manually crafted new gist](https://gist.github.com/rugk/b7886c7332dac68d9b83ed534b5062e0) results in a server response https://projectfluent.org/play/?gist=b7886c7332dac68d9b83ed534b5062e0, but the whole page is just empty and I get plenty of JS errors.

**Comment by stasm** [comment]
Thanks for filing this and for the extra effort of creating a manually crafted gist. It looks like this is a problem with Babel's `regeneratorRuntime`; I'll try to fix it today.

**Comment by stasm** [comment]
Because the domain should read `projectfluent.org` rather than `.io` :)

**Comment by stasm** [comment]
Alright, I fixed this in https://github.com/projectfluent/play/commit/1c00c6d95df849a235036cf2054f45d6f130e722. The second URL works now.

**Comment by rugk** [comment]
> Because the domain should read projectfluent.org rather than .io :)

Ugh... 😆 
That was some old link then...

**Comment by rugk** [comment]
>  The second URL works now.

I can confirm that it works now.
